kind: pipeline
type: docker
name: default

workspace:
  base: /go/src
  path: ${DRONE_REPO_NAME}

## 禁止默認 clone 行為
clone:
  disable: true

steps:
  ## clone 專案
  - name: clone
    image: evergreen.guardians.one/rd3/drone-git:latest
    environment:
      RSYNC_KEY:
        from_secret: rsync_key
    commands:
      # 隨機 sleep 1-10 秒
      - sleep $(shuf -i 1-10 -n 1)

      ## add git config
      - git config --global user.name "drone"
      - git config --global user.email "drone@cchntek.com"
      - mkdir ~/.ssh
      - echo "$RSYNC_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      ## add to known hosts
      - ssh-keyscan -H git.cchntek.com >> ~/.ssh/known_hosts
      - ssh-keyscan -H gitlab.cqgame.info >> ~/.ssh/known_hosts
      ## git clone & git submodule
      - git clone ${DRONE_GIT_SSH_URL} .
      - git checkout $DRONE_COMMIT
      - git submodule update --recursive --init
    when:
      ref: [ refs/heads/develop, refs/heads/qatest, refs/heads/int, refs/tags/v*, refs/tags/t* ]
  ## 設定 dev tag
  - name: set-tag
    image: evergreen.guardians.one/rd3/drone-git:latest
    commands:
      - echo "$(git rev-parse --short=7 ${DRONE_COMMIT_SHA})-${DRONE_BRANCH}" > ./tmp.txt
      - cat ./tmp.txt > .tags
      - echo ",latest-${DRONE_BRANCH}" >> .tags
    when:
      ref: [ refs/heads/develop, refs/heads/qatest, refs/heads/int ]
    depends_on:
      - clone
  ## 設定 prod tag
  - name: backup-pro-tag
    image: evergreen.guardians.one/rd3/drone-git:latest
    commands:
      - echo ${DRONE_TAG}  > ./tmp.txt
      - cat ./tmp.txt > .tags
      - echo ",latest-prod" >> .tags
    when:
      ref: [ refs/tags/v*, refs/tags/t* ]
    depends_on:
      - clone
  ## 建置容器並傳至 harbor (INT Project)
  - name: build-image
    image: evergreen.guardians.one/rd3/drone-docker:18.09.6
    environment:
      PROJECT_NAME: ${DRONE_REPO_NAME}
      ACCESS_TOKEN:
        from_secret: access_token
    settings:
      registry: evergreen.guardians.one
      repo: evergreen.guardians.one/rd3/golang-${DRONE_REPO_NAME}
      dockerfile: ./k8s.Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args_from_env:
        - ACCESS_TOKEN
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      ref: [ refs/heads/develop, refs/heads/qatest, refs/heads/int ]
    depends_on:
      - set-tag
      - backup-pro-tag
  ## 建置容器並傳至 harbor (T2 Project)
  - name: build-sync-images
    image: evergreen.guardians.one/rd3/drone-docker:18.09.6
    environment:
      PROJECT_NAME: ${DRONE_REPO_NAME}
      ACCESS_TOKEN:
        from_secret: access_token
    settings:
      registry: evergreen.guardians.one
      repo: evergreen.guardians.one/rd3/golang-${DRONE_REPO_NAME}
      dockerfile: ./k8s.Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args_from_env:
        - ACCESS_TOKEN
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      ref: [ refs/tags/v*, refs/tags/t* ]
    depends_on:
      - set-tag
      - backup-pro-tag
  ## 重新覆蓋 .tag 檔案內容
  - name: rebuild-tag-file
    image: evergreen.guardians.one/rd3/drone-git:latest
    commands:
      - cat ./tmp.txt > .tags
      - cat .tags
    when:
      ref: [ refs/heads/develop, refs/heads/qatest, refs/heads/int, refs/tags/v*, refs/tags/t* ]
    depends_on:
      - build-image
      - build-sync-images
  ## 佈署至 dev k8s 環境
  - name: deploy-dev-k8s
    image: evergreen.guardians.one/rd3/drone-kubernetes:latest
    settings:
      kubernetes_server: https://f4.guardians.one/k8s/clusters/c-hswpk
      namespace: rd3-dev-${DRONE_REPO_NAME}
      deployment: dev-${DRONE_REPO_NAME}-deployment
      repo: evergreen.guardians.one/rd3/golang-${DRONE_REPO_NAME}
      container: dev-${DRONE_REPO_NAME}
      use_tags_file: true
      kubernetes_token:
        from_secret: kubernetes_token_dev
    when:
      ref: [ refs/heads/develop ]
    depends_on:
      - rebuild-tag-file
  ## 佈署至 qa k8s 環境
  - name: deploy-qa-k8s
    image: evergreen.guardians.one/rd3/drone-kubernetes:latest
    settings:
      kubernetes_server: https://f4.guardians.one/k8s/clusters/c-pzbf4
      namespace: rd3-qa-${DRONE_REPO_NAME}
      deployment: qa-${DRONE_REPO_NAME}-deployment
      repo: evergreen.guardians.one/rd3/golang-${DRONE_REPO_NAME}
      container: qa-${DRONE_REPO_NAME}
      use_tags_file: true
      kubernetes_token:
        from_secret: kubernetes_token_qa
    when:
      ref: [ refs/heads/qatest ]
    depends_on:
      - rebuild-tag-file
  ## 佈署至 int k8s 環境
  - name: deploy-int-k8s
    image: evergreen.guardians.one/rd3/drone-kubernetes:latest
    settings:
      kubernetes_server: https://f4.guardians.one/k8s/clusters/c-cvs7s
      namespace: rd3-int-${DRONE_REPO_NAME}
      deployment: int-${DRONE_REPO_NAME}-deployment
      repo: evergreen.guardians.one/rd3/golang-${DRONE_REPO_NAME}
      container: int-${DRONE_REPO_NAME}
      use_tags_file: true
      kubernetes_token:
        from_secret: kubernetes_token_int
    when:
      ref: [ refs/heads/int ]
    depends_on:
      - rebuild-tag-file
  ## 佈署至 pro t2 k8s 環境
  - name: deploy-pro-t2-k8s
    image: evergreen.guardians.one/rd3/drone-kubernetes:latest
    settings:
      kubernetes_server: https://k8s.t2.corp/k8s/clusters/c-9cb7h
      namespace: rd3-pro-${DRONE_REPO_NAME}
      deployment: pro-${DRONE_REPO_NAME}-deployment
      repo: xn--85809-rt8hx48m.guardians.one/rd3-sync/golang-${DRONE_REPO_NAME}
      container: pro-${DRONE_REPO_NAME}
      tag: ${DRONE_TAG}
      kubernetes_token:
        from_secret: kubernetes_token_t2
    when:
      ref: [ refs/tags/v* ]
    depends_on:
      - rebuild-tag-file
  ## Telegram 推播通知
  - name: telegram
    image: evergreen.guardians.one/rd3/drone-telegram:1.3.5
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_to
      format: markdown
      message:  >
        {{#success build.status}}
        ✅ Build #{{build.number}} of `{{repo.name}}` succeeded.

        📝 Commit by `{{commit.author}}` on `{{commit.branch}}`:

        ```
        {{commit.message}}
        ```

        🌐 {{ build.link }}
        {{else}}
        ❌ Build #{{build.number}} of `{{repo.name}}` failed.

        📝  Commit by `{{commit.author}}` on `{{commit.branch}}`:

        ```
        {{commit.message}}
        ```
        🌐 {{ build.link }}
        {{/success}}


        〰️〰️〰️〰️〰️〰️〰️〰️〰️〰️
    when:
      status:
        - success
        - failure
    depends_on:
      - deploy-dev-k8s
      - deploy-qa-k8s
      - deploy-int-k8s
      - deploy-pro-t2-k8s



## VM 掛載路徑
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

## 觸發 pipeline 條件
trigger:
  ref:
    include:
      - refs/heads/develop
      - refs/heads/qatest
      - refs/heads/int
      - refs/tags/v*
      - refs/tags/t*
