settings:
  legacy:
    force: false
    interval: 100ms
schema:
- name: GoFormat
  path: .
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    - yaml
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
