version: '3'

services:
  goformat-db:
    image: mariadb
    container_name: GoFormatDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # DB 密碼
      MYSQL_DATABASE: goformat  # 資料庫名稱
    volumes:
      - /home/GoFormat/database:/var/lib/mysql
    networks:
      - web_service
  golang:
    image: nexus.cqgame.games/rd3/golang-goformat:latest
    # build:
    #   context: .
    container_name: ${PROJECT_NAME}
    restart: always
    ports:
      - 9999:8080
    environment:
      - ENV=${ENV} # 各站環境變數
      - PROJECT_NAME=${PROJECT_NAME} # 專案名稱
    working_dir: /go/src/${PROJECT_NAME}
    volumes:
      - .:/go/src/${PROJECT_NAME}
      - ${LOG}:/app/log/
      - ${IMG}:/home/images
      - /etc/localtime:/etc/localtime:ro # 美東時間
      - ./linux_conf/logrotate:/etc/logrotate.d/${PROJECT_NAME} # 掛載logrotate 規則
      - ./linux_conf/supervisor.ini:/etc/supervisor.d/${PROJECT_NAME}.ini # 掛載 supervisor 起服務規則
    networks:
      - web_service
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"


networks:
  web_service:
    external: true