version: '3'

services:
  goformat-db:
    image: mariadb
    container_name: goformatDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # DB 密碼
      MYSQL_DATABASE: goformat  # 資料庫名稱
    volumes:
      - /home/goformat/database:/var/lib/mysql
    networks:
      - web_service
      
  golang-goformat:
    # image: nexus.cqgame.games/rd3/golang-goformat:latest
    build:
      context: .
    container_name: ${PROJECT_NAME}
    restart: always
    # ports:
    #   - 9999:8080
    environment:
      - ENV=${ENV} # 各站環境變數
      - SERVICE=all
      - PROJECT_NAME=${PROJECT_NAME} # 專案名稱
    working_dir: /go/src/${PROJECT_NAME}
    volumes:
      - .:/go/src/${PROJECT_NAME}
      - ${IMG}:/app/images
    labels:
      - "traefik.http.routers.golang-goformat.rule=Host(`goformat.local.com`)"
      - "traefik.http.services.golang-goformat.loadbalancer.server.port=8080"
    networks:
      - web_service
    command: "fresh runner.conf"

  redis-goformat:
    image: nexus.cqgame.games/rd3/library-redis:alpine
    container_name: redis_goFormat
    # 設定最大的TCP連線
    sysctls:
      net.core.somaxconn: 4096
    restart: always
    volumes:
      - ./Redis/goformat:/data
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    # 指定使用那一條網路
    networks:
      - web_service



networks:
  web_service:
    external: true