version: '3'

services:
  goformat-db:
    image: mariadb
    container_name: ${PROJECT_NAME}DB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # DB 密碼
      MYSQL_DATABASE: ${PROJECT_NAME}  # 資料庫名稱
    volumes:
      - /home/${PROJECT_NAME}/database:/var/lib/mysql
    networks:
      - web_service
      
  golang-goformat:
    # image: nexus.cqgame.games/rd3/golang-${PROJECT_NAME}:latest
    build:
      context: .
    container_name: ${PROJECT_NAME}
    restart: always
    # ports:
    #   - 9999:8080
    environment:
      - ENV=${ENV} # 各站環境變數
      - SERVICE=all
      - PROJECT_NAME=${PROJECT_NAME} # 專案名稱
      - GOPRIVATE=${GITLAB} # GO Private 網址
      # - GONOPROXY=${GOPROXY} # GO Proxy 網址
    working_dir: /go/src/${PROJECT_NAME}
    volumes:
      - .:/go/src/${PROJECT_NAME}
      - ${IMG}:/app/images
    labels:
      - "traefik.http.routers.golang-${PROJECT_NAME}.rule=Host(`${PROJECT_NAME}.local.com`)"
      - "traefik.http.services.golang-${PROJECT_NAME}.loadbalancer.server.port=8080"
    networks:
      - web_service
    command: "fresh runner.conf"

  redis-goformat:
    image: nexus.cqgame.games/rd3/library-redis:alpine
    container_name: redis_${PROJECT_NAME}
    # 設定最大的TCP連線
    sysctls:
      net.core.somaxconn: 4096
    restart: always
    volumes:
      - ./Redis/${PROJECT_NAME}:/data
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    # 指定使用那一條網路
    networks:
      - web_service



networks:
  web_service:
    external: true