version: '3'

services:
  golang:
    image: harbor.rd3sit.com/golang/goformat:latest
    # build:
    #   context: .
    container_name: ${PROJECT_NAME}
    restart: always
    ports:
      - 9999:8080
    environment:
      - ENV=${ENV} # 各站環境變數
      - PROJECT_NAME=${PROJECT_NAME}
    working_dir: /go/src/${PROJECT_NAME}
    volumes:
      - .:/go/src/${PROJECT_NAME}
      - ${LOG}:/home/log
      - ${IMG}:/home/images
      - /etc/localtime:/etc/localtime:ro # 美東時間
      - ./supervisor.ini:/etc/supervisor.d/supervisor.ini
      - ./logrotate:/etc/logrotate.d/${PROJECT_NAME}
    networks:
      - web_service
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
networks:
  web_service:
    external: true